apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nl0yun59b-go
  janus-idp.io/tekton: nl0yun59b-go
  backstage.io/kubernetes-id: nl0yun59b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nl0yun59b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
